# Generated by Django 5.0.6 on 2025-07-08 19:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "mcp_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("participant", "Participante"),
                            ("voter", "Eleitor"),
                            ("admin", "Administrador"),
                            ("mentor", "Mentor"),
                            ("donor", "Contribuinte"),
                        ],
                        default="voter",
                        max_length=20,
                        verbose_name="Tipo de Utilizador",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?244\\d{9}$",
                                "Número de telefone angolano inválido",
                            )
                        ],
                        verbose_name="Número de Telefone",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("luanda", "Luanda"),
                            ("benguela", "Benguela"),
                            ("huila", "Huíla"),
                            ("namibe", "Namibe"),
                            ("cunene", "Cunene"),
                            ("huambo", "Huambo"),
                            ("bie", "Bié"),
                            ("malanje", "Malanje"),
                            ("lunda_norte", "Lunda Norte"),
                            ("lunda_sul", "Lunda Sul"),
                            ("moxico", "Moxico"),
                            ("cuando_cubango", "Cuando Cubango"),
                            ("cabinda", "Cabinda"),
                            ("zaire", "Zaire"),
                            ("uige", "Uíge"),
                            ("bengo", "Bengo"),
                            ("cuanza_norte", "Cuanza Norte"),
                            ("cuanza_sul", "Cuanza Sul"),
                        ],
                        max_length=50,
                        verbose_name="Província",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="Cidade"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/",
                        verbose_name="Imagem de Perfil",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Biografia"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(default=False, verbose_name="Termos Aceites"),
                ),
                (
                    "newsletter_subscription",
                    models.BooleanField(
                        default=True, verbose_name="Subscrição Newsletter"
                    ),
                ),
                (
                    "preferencia_comunicacao_formal",
                    models.BooleanField(
                        default=True,
                        help_text="Receber comunicações em formato formal angolano",
                        verbose_name="Comunicação Formal",
                    ),
                ),
                (
                    "mcp_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados para comunicação MCP",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilizador",
                "verbose_name_plural": "Utilizadores",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter")),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("pt", "Português"), ("en", "English")],
                        default="pt",
                        max_length=10,
                        verbose_name="Idioma Preferido",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notificações por Email"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Notificações por SMS"
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar Email Publicamente"
                    ),
                ),
                (
                    "show_phone",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar Telefone Publicamente"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Utilizador",
                "verbose_name_plural": "Perfis de Utilizadores",
            },
        ),
    ]
