# Generated by Django 5.0.6 on 2025-08-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mcp_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mcp_metadata",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferencia_comunicacao_formal",
        ),
        migrations.AlterField(
            model_name="user",
            name="province",
            field=models.CharField(blank=True, max_length=50, verbose_name="Província"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("participant", "Participante"),
                    ("voter", "Eleitor"),
                    ("admin", "Administrador"),
                    ("mentor", "Mentor"),
                ],
                default="voter",
                max_length=20,
                verbose_name="Tipo de Utilizador",
            ),
        ),
    ]
