# Generated by Django 6.0 on 2025-12-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_mcp_id_remove_user_mcp_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagem de Perfil'),
        ),
    ]
