# Generated by Django 5.0.6 on 2025-12-28 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verificado')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Telefone Verificado')),
                ('profile_complete', models.BooleanField(default=False, verbose_name='Perfil Completo')),
                ('votes_cast', models.IntegerField(default=0, verbose_name='Votos Realizados')),
                ('content_published', models.IntegerField(default=0, verbose_name='Conteúdo Publicado')),
                ('positive_feedback_received', models.IntegerField(default=0, verbose_name='Feedback Positivo')),
                ('reports_filed', models.IntegerField(default=0, verbose_name='Reportes Enviados')),
                ('sales_completed', models.IntegerField(default=0, verbose_name='Vendas Completas')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Rating Médio')),
                ('dispute_count', models.IntegerField(default=0, verbose_name='Disputas')),
                ('account_age_days', models.IntegerField(default=0, verbose_name='Idade da Conta (dias)')),
                ('last_flagged_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Flag')),
                ('flag_reason', models.CharField(blank=True, max_length=255, verbose_name='Razão da Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pontuação de Confiança',
                'verbose_name_plural': 'Pontuações de Confiança',
            },
        ),
    ]
