# Generated by Django 5.0.6 on 2025-12-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usertrustscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrustscore',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Código de Verificação de Email'),
        ),
        migrations.AddField(
            model_name='usertrustscore',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio do Código de Email'),
        ),
    ]
