# Generated by Django 5.0.6 on 2025-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usertrustscore_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrustscore',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Código de Verificação de Telefone'),
        ),
        migrations.AddField(
            model_name='usertrustscore',
            name='phone_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio do Código de Telefone'),
        ),
    ]
