# Generated by Django 6.0 on 2025-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do patrocinador/parceiro', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do patrocinador/parceiro', null=True)),
                ('logo', models.URLField(help_text='URL do logo do patrocinador/parceiro')),
                ('url', models.URLField(blank=True, help_text='Website ou link do patrocinador', null=True)),
                ('sponsor_type', models.CharField(choices=[('sponsor', 'Patrocinador'), ('partner', 'Parceiro'), ('supporter', 'Apoiador')], default='partner', help_text='Tipo de patrocínio', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (ascendente)')),
                ('is_active', models.BooleanField(default=True, help_text='Se o patrocinador deve ser exibido')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de última atualização')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['order', 'name'],
            },
        ),
    ]
