# Generated by Django 5.0.6 on 2025-07-08 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_number",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Número do Participante",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("active", "Ativo"),
                            ("eliminated", "Eliminado"),
                            ("winner", "Vencedor"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=100, verbose_name="Nome do Negócio"),
                ),
                (
                    "business_category",
                    models.CharField(
                        choices=[
                            ("technology", "Tecnologia"),
                            ("agriculture", "Agricultura"),
                            ("education", "Educação"),
                            ("health", "Saúde"),
                            ("commerce", "Comércio"),
                            ("services", "Serviços"),
                            ("manufacturing", "Indústria"),
                            ("tourism", "Turismo"),
                            ("arts", "Artes e Cultura"),
                            ("other", "Outros"),
                        ],
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "business_description",
                    models.TextField(verbose_name="Descrição do Negócio"),
                ),
                (
                    "pitch_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pitches/videos/",
                        verbose_name="Vídeo de Apresentação",
                    ),
                ),
                (
                    "pitch_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pitches/documents/",
                        verbose_name="Documento de Apresentação",
                    ),
                ),
                (
                    "mentor_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pontuação do Mentor",
                    ),
                ),
                (
                    "public_votes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Votos do Público"
                    ),
                ),
                (
                    "funding_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Meta de Financiamento",
                    ),
                ),
                (
                    "funding_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Financiamento Recebido",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("due_date", models.DateTimeField(verbose_name="Data Limite")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Progresso"),
                            ("completed", "Concluída"),
                            ("overdue", "Atrasada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "submission",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="task_submissions/",
                        verbose_name="Submissão",
                    ),
                ),
                (
                    "submission_notes",
                    models.TextField(blank=True, verbose_name="Notas da Submissão"),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pontuação",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Feedback")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tarefa do Participante",
                "verbose_name_plural": "Tarefas dos Participantes",
                "ordering": ["due_date"],
            },
        ),
    ]
