# Generated by Django 5.0.6 on 2025-07-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
        ("seasons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="episode_eliminated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eliminated_participants",
                to="seasons.episode",
                verbose_name="Episódio de Eliminação",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="episode_joined",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seasons.episode",
                verbose_name="Episódio de Entrada",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="seasons.season",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participanttask",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="participants.participant",
            ),
        ),
    ]
