# Generated by Django 5.0.6 on 2025-08-21 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
        ('seasons', '0003_episode_is_deleted_episode_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='seasons.season', verbose_name='Temporada'),
        ),
    ]
