# Generated by Django 6.0 on 2025-12-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_season'),
        ('participants', '0004_participant_primary_savings_group'),
    ]

    operations = [
    ]
