# Generated by Django 6.0 on 2025-12-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kixikila', '0001_initial'),
        ('participants', '0005_merge_20251212_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='primary_savings_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_participants', to='kixikila.kixikilagroup', verbose_name='Grupo de Poupança Principal'),
        ),
    ]
