# Generated by Django 5.0.6 on 2025-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_question_rename_name_game_title_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='assets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='feedback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='game',
            name='ranking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('simulator', 'Simulador'), ('association', 'Associação'), ('crosswords', 'Palavras Cruzadas')], default='quiz', max_length=50),
        ),
    ]
