# Generated by Django 5.2.5 on 2025-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamesession_feedback_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='season_number',
            field=models.PositiveIntegerField(default=1, help_text='Season number for harmonization'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='season_number',
            field=models.PositiveIntegerField(default=1, help_text='Season number for harmonization'),
        ),
    ]
