# Generated by Django 5.0.6 on 2025-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gamesession_season_number_quiz_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='simulator',
            name='kpi_targets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='simulator',
            name='scenario_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
