# Generated by Django 6.0 on 2025-12-14 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_simulator_difficulty_simulator_kpi_targets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField(db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('access_type', models.CharField(choices=[('public', 'Acesso Público'), ('authenticated', 'Acesso Autenticado'), ('admin', 'Acesso Administrativo')], max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Quiz Access Log',
                'verbose_name_plural': 'Quiz Access Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_anonymous_submission',
            field=models.BooleanField(default=True, help_text='Se True, usuários anônimos podem submeter respostas'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='authenticated_access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se True, o quiz está disponível para acesso'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='public_access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Se True, permite acesso público sem autenticação'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['season_number', 'is_active'], name='games_quiz_season__196df8_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_public', 'is_active'], name='games_quiz_is_publ_429f73_idx'),
        ),
        migrations.AddField(
            model_name='quizaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='quizaccesslog',
            index=models.Index(fields=['quiz_id', '-created_at'], name='games_quiza_quiz_id_a44d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='quizaccesslog',
            index=models.Index(fields=['user', '-created_at'], name='games_quiza_user_id_f0088a_idx'),
        ),
        migrations.AddIndex(
            model_name='quizaccesslog',
            index=models.Index(fields=['ip_address', '-created_at'], name='games_quiza_ip_addr_ce66bd_idx'),
        ),
    ]
