# Generated by Django 6.0 on 2025-12-14 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_crossword_crosswordsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossword',
            name='clues',
        ),
        migrations.AddField(
            model_name='crosswordsession',
            name='time_taken',
            field=models.PositiveIntegerField(default=0, help_text='Time in seconds'),
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, default='Médio', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssociationPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(help_text='Conceito/termo', max_length=200)),
                ('right_item', models.CharField(help_text='Definição/correspondência', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='games.association')),
            ],
            options={
                'ordering': ['association', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssociationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.JSONField(blank=True, default=dict, help_text='User matches: {left: right}')),
                ('score', models.PositiveIntegerField(default=0)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CrosswordClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_text', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('across', 'Horizontal'), ('down', 'Vertical')], default='across', max_length=10)),
                ('number', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('crossword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='games.crossword')),
            ],
            options={
                'ordering': ['crossword', 'order'],
            },
        ),
    ]
