# Generated by Django 5.0.6 on 2026-01-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_remove_crossword_clues_crosswordsession_time_taken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="asset_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="game",
            name="difficulty",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="game",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
