# Generated by Django 5.0.6 on 2025-12-09 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria profissional', max_length=200, unique=True)),
                ('inefob_code', models.CharField(help_text='Código INEFOB para esta categoria', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Descrição detalhada da profissão')),
                ('icon_url', models.URLField(blank=True, help_text='URL do ícone da categoria', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Categoria ativa ou arquivada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Professional Categories',
                'db_table': 'certifications_professionalcategory',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['inefob_code'], name='certificati_inefob__44419c_idx'), models.Index(fields=['is_active'], name='certificati_is_acti_239b5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do programa de formação', max_length=200)),
                ('description', models.TextField(help_text='Descrição detalhada do programa')),
                ('provider', models.CharField(help_text='Provedor/instituição da formação', max_length=200)),
                ('duration_hours', models.IntegerField(help_text='Duração total em horas')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Custo do programa em AOA', max_digits=10)),
                ('is_inefob_certified', models.BooleanField(default=False, help_text='Certificado pelo INEFOB')),
                ('is_active', models.BooleanField(default=True, help_text='Programa ativo ou arquivado')),
                ('max_participants', models.IntegerField(blank=True, help_text='Limite de participantes (null = ilimitado)', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Data de início do programa', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Data de término do programa', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Categoria profissional', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='certifications.professionalcategory')),
            ],
            options={
                'db_table': 'certifications_trainingprogram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da avaliação', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição dos critérios')),
                ('weight', models.IntegerField(default=100, help_text='Peso relativo (%)')),
                ('is_required', models.BooleanField(default=True, help_text='Obrigatório para certificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='certifications.trainingprogram')),
            ],
            options={
                'db_table': 'certifications_skillassessment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Inscrito'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído'), ('certified', 'Certificado'), ('failed', 'Reprovado'), ('cancelled', 'Cancelado')], default='enrolled', max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('certificate_code', models.CharField(blank=True, help_text='Código único do certificado', max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_enrollments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='certifications.trainingprogram')),
            ],
            options={
                'db_table': 'certifications_candidateenrollment',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Aprovado'), ('fail', 'Reprovado'), ('pending', 'Pendente')], default='pending', max_length=20)),
                ('score', models.IntegerField(blank=True, help_text='Pontuação (0-100)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_evaluated', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='certifications.candidateenrollment')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='certifications.skillassessment')),
            ],
            options={
                'db_table': 'certifications_assessmentresult',
                'ordering': ['-evaluated_at'],
                'indexes': [models.Index(fields=['enrollment', 'result'], name='certificati_enrollm_fcc98f_idx')],
                'unique_together': {('enrollment', 'assessment')},
            },
        ),
        migrations.AddIndex(
            model_name='trainingprogram',
            index=models.Index(fields=['category', 'is_active'], name='certificati_categor_25f554_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingprogram',
            index=models.Index(fields=['is_inefob_certified'], name='certificati_is_inef_c6d495_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateenrollment',
            index=models.Index(fields=['candidate', 'status'], name='certificati_candida_7521a5_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateenrollment',
            index=models.Index(fields=['program', 'status'], name='certificati_program_c033e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateenrollment',
            unique_together={('candidate', 'program')},
        ),
    ]
