# Generated by Django 5.0.6 on 2025-08-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='content_media/'),
        ),
    ]
