# Generated by Django 5.0.6 on 2025-07-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
        ("seasons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email do Eleitor",
                    ),
                ),
                (
                    "voter_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone do Eleitor",
                    ),
                ),
                (
                    "voter_ip",
                    models.GenericIPAddressField(verbose_name="IP do Eleitor"),
                ),
                ("weight", models.IntegerField(default=1, verbose_name="Peso do Voto")),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Comentário"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Token de Verificação"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_votes",
                        to="participants.participant",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto",
                "verbose_name_plural": "Votos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VotingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("start_date", models.DateTimeField(verbose_name="Data de Início")),
                ("end_date", models.DateTimeField(verbose_name="Data de Fim")),
                (
                    "max_votes_per_user",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Máximo de Votos por Utilizador"
                    ),
                ),
                (
                    "requires_registration",
                    models.BooleanField(default=False, verbose_name="Requer Registo"),
                ),
                (
                    "show_results_live",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar Resultados em Tempo Real"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Próxima"),
                            ("active", "Ativa"),
                            ("paused", "Pausada"),
                            ("completed", "Concluída"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_session",
                        to="seasons.episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Votação",
                "verbose_name_plural": "Sessões de Votação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VotingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("duplicate", "Voto Duplicado"),
                            ("fake", "Voto Falso"),
                            ("bot", "Voto Automatizado"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "reporter_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email do Denunciante"
                    ),
                ),
                (
                    "reporter_ip",
                    models.GenericIPAddressField(verbose_name="IP do Denunciante"),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(default=False, verbose_name="Revisto"),
                ),
                (
                    "is_valid",
                    models.BooleanField(blank=True, null=True, verbose_name="Válido"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notas do Administrador"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="voting.vote",
                    ),
                ),
                (
                    "voting_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="voting.votingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de Votação",
                "verbose_name_plural": "Relatórios de Votação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="vote",
            name="voting_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="voting.votingsession",
            ),
        ),
        migrations.CreateModel(
            name="VotingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de Votos"
                    ),
                ),
                (
                    "vote_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Percentagem de Votos",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Posição"
                    ),
                ),
                (
                    "verified_votes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Votos Verificados"
                    ),
                ),
                (
                    "weighted_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Pontuação Ponderada",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_results",
                        to="participants.participant",
                    ),
                ),
                (
                    "voting_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="voting.votingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Votação",
                "verbose_name_plural": "Resultados de Votação",
                "ordering": ["-vote_count"],
                "unique_together": {("voting_session", "participant")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={
                ("voting_session", "voter"),
                ("voting_session", "voter_email"),
                ("voting_session", "voter_phone"),
            },
        ),
    ]
