# Generated by Django 6.0 on 2025-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='image',
            field=models.URLField(blank=True, help_text='URL da imagem da campanha', null=True, verbose_name='URL da Imagem da Campanha'),
        ),
    ]
