# Generated by Django 5.0.6 on 2025-07-08 19:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "goal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Meta de Arrecadação",
                    ),
                ),
                (
                    "raised_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Arrecadado",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Data de Início")),
                ("end_date", models.DateTimeField(verbose_name="Data de Fim")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="campaigns/",
                        verbose_name="Imagem da Campanha",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="Vídeo da Campanha"),
                ),
                (
                    "min_donation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=10,
                        verbose_name="Doação Mínima",
                    ),
                ),
                (
                    "max_donation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Doação Máxima",
                    ),
                ),
                (
                    "anonymous_allowed",
                    models.BooleanField(
                        default=True, verbose_name="Permitir Doações Anónimas"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativa"),
                            ("paused", "Pausada"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campanha de Doações",
                "verbose_name_plural": "Campanhas de Doações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Alvo"
                    ),
                ),
                (
                    "reward_description",
                    models.TextField(
                        blank=True, verbose_name="Descrição da Recompensa"
                    ),
                ),
                (
                    "is_achieved",
                    models.BooleanField(default=False, verbose_name="Alcançado"),
                ),
                (
                    "achieved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Alcance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Meta de Doação",
                "verbose_name_plural": "Metas de Doação",
                "ordering": ["target_amount"],
            },
        ),
        migrations.CreateModel(
            name="DonationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                            ("campaign", "Por Campanha"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                ("end_date", models.DateField(verbose_name="Data de Fim")),
                (
                    "total_donations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de Doações"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "total_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total de Taxas",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Líquido",
                    ),
                ),
                (
                    "unique_donors",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Doadores Únicos"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Relatório de Doações",
                "verbose_name_plural": "Relatórios de Doações",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(max_length=100, verbose_name="Nome do Doador"),
                ),
                (
                    "donor_email",
                    models.EmailField(max_length=254, verbose_name="Email do Doador"),
                ),
                (
                    "donor_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Telefone do Doador"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Doação Anónima"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="AOA", max_length=3, verbose_name="Moeda"),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Mensagem"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("multicaixa", "Multicaixa Express"),
                            ("bank_transfer", "Transferência Bancária"),
                            ("mobile_money", "Dinheiro Móvel"),
                        ],
                        max_length=20,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Referência de Pagamento",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID da Transação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Concluída"),
                            ("failed", "Falhada"),
                            ("refunded", "Reembolsada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Taxa de Processamento",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Líquido"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receipt_sent",
                    models.BooleanField(default=False, verbose_name="Recibo Enviado"),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número do Recibo"
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doação",
                "verbose_name_plural": "Doações",
                "ordering": ["-created_at"],
            },
        ),
    ]
