# Generated by Django 5.0.6 on 2025-07-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        ("participants", "0001_initial"),
        ("seasons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationcampaign",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="participants.participant",
                verbose_name="Participante",
            ),
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="seasons.season",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="donations.donationcampaign",
            ),
        ),
        migrations.AddField(
            model_name="donationgoal",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="donations.donationcampaign",
            ),
        ),
    ]
