# Generated by Django 6.0 on 2025-12-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicelisting',
            name='marketplace_availab_33dd16_idx',
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='listing_type',
            field=models.CharField(choices=[('service', 'Serviço'), ('product', 'Produto')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='quantity_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['listing_type', 'available'], name='marketplace_listing_a04cee_idx'),
        ),
    ]
