# Generated by Django 6.0 on 2025-12-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_servicelisting_marketplace_availab_33dd16_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='provider_type',
            field=models.CharField(choices=[('service_provider', 'Prestador de Serviço'), ('merchant', 'Comerciante')], default='service_provider', max_length=20),
        ),
    ]
