# Generated by Django 5.0.6 on 2025-12-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        ('marketplace', '0003_serviceprovider_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='professional_category',
            field=models.ForeignKey(blank=True, help_text='Categoria profissional INEFOB (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_providers', to='certifications.professionalcategory'),
        ),
    ]
