# Generated by Django 5.0.6 on 2025-07-08 19:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "season_number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Número da Temporada"
                    ),
                ),
                (
                    "registration_start",
                    models.DateTimeField(verbose_name="Início das Inscrições"),
                ),
                (
                    "registration_end",
                    models.DateTimeField(verbose_name="Fim das Inscrições"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Data de Início")),
                ("end_date", models.DateTimeField(verbose_name="Data de Fim")),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Máximo de Participantes"
                    ),
                ),
                (
                    "prize_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor do Prémio",
                    ),
                ),
                (
                    "poster_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seasons/posters/",
                        verbose_name="Imagem da Temporada",
                    ),
                ),
                (
                    "trailer_video",
                    models.URLField(blank=True, verbose_name="Vídeo Promocional"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Próxima"),
                            ("registration_open", "Inscrições Abertas"),
                            ("active", "Ativa"),
                            ("completed", "Concluída"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Temporada Atual"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Temporada",
                "verbose_name_plural": "Temporadas",
                "ordering": ["-season_number"],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_number",
                    models.PositiveIntegerField(verbose_name="Número do Episódio"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("air_date", models.DateTimeField(verbose_name="Data de Transmissão")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Duração (minutos)"
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="URL do Vídeo")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="episodes/thumbnails/",
                        verbose_name="Miniatura",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visualizações"
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="Likes"),
                ),
                (
                    "has_elimination",
                    models.BooleanField(default=False, verbose_name="Tem Eliminação"),
                ),
                (
                    "voting_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Votação Habilitada"
                    ),
                ),
                (
                    "voting_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim da Votação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Próximo"),
                            ("live", "Ao Vivo"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="seasons.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Episódio",
                "verbose_name_plural": "Episódios",
                "ordering": ["season", "episode_number"],
                "unique_together": {("season", "episode_number")},
            },
        ),
        migrations.CreateModel(
            name="EpisodeParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performance_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pontuação de Performance",
                    ),
                ),
                (
                    "mentor_feedback",
                    models.TextField(blank=True, verbose_name="Feedback do Mentor"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Em Destaque"),
                ),
                (
                    "is_eliminated",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_participants",
                        to="seasons.episode",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante do Episódio",
                "verbose_name_plural": "Participantes dos Episódios",
                "unique_together": {("episode", "participant")},
            },
        ),
    ]
