# Generated by Django 5.0.6 on 2025-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeparticipant',
            name='vote_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Votos Recebidos'),
        ),
    ]
