# Generated by Django 5.0.6 on 2025-08-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_episodeparticipant_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Removido'),
        ),
        migrations.AddField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='episodeparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='episodeparticipant',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Número do Episódio'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'episode_number'], name='seasons_epi_season__536794_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['status'], name='seasons_epi_status_461566_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['air_date'], name='seasons_epi_air_dat_5491eb_idx'),
        ),
    ]
