# Generated by Django 6.0 on 2025-12-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_episode_is_deleted_episode_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='season',
            name='poster_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagem da Temporada'),
        ),
    ]
