# Generated by Django 5.0.6 on 2025-12-09 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KixikilaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_type', models.CharField(choices=[('professional', 'Profissional'), ('neighborhood', 'Bairro'), ('family', 'Familiar'), ('business', 'Empresarial')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_members', models.PositiveIntegerField()),
                ('current_members', models.PositiveIntegerField(default=0)),
                ('duration_months', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('requires_verification', models.BooleanField(default=True)),
                ('min_reputation_score', models.IntegerField(default=0)),
                ('insurance_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('forming', 'Formando'), ('active', 'Ativo'), ('completed', 'Concluído'), ('suspended', 'Suspenso')], default='forming', max_length=50)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_kixikila_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KixikilaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('position_priority', models.CharField(choices=[('random', 'Aleatória'), ('auction', 'Leilão'), ('need_based', 'Baseada em necessidade')], default='random', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('contributions_made', models.PositiveIntegerField(default=0)),
                ('payout_received', models.BooleanField(default=False)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('collateral_type', models.CharField(blank=True, max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='kixikila.kixikilagroup')),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_kixikila_members', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kixikila_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'position'],
            },
        ),
        migrations.CreateModel(
            name='KixikilaContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('late', 'Atrasada'), ('missed', 'Falhada')], default='pending', max_length=50)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='kixikila.kixikilamembership')),
            ],
            options={
                'ordering': ['membership', 'round'],
            },
        ),
        migrations.CreateModel(
            name='KixikilaPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scheduled_date', models.DateField()),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('processing', 'A processar'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='scheduled', max_length=50)),
                ('intended_use', models.CharField(blank=True, max_length=200)),
                ('proof_of_use', models.FileField(blank=True, null=True, upload_to='kixikila_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='kixikila.kixikilagroup')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kixikila_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='KixikilaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_participated', models.PositiveIntegerField(default=0)),
                ('contributions_on_time', models.PositiveIntegerField(default=0)),
                ('contributions_late', models.PositiveIntegerField(default=0)),
                ('contributions_missed', models.PositiveIntegerField(default=0)),
                ('reputation_score', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trust_level', models.CharField(choices=[('beginner', 'Iniciante'), ('reliable', 'Confiável'), ('trusted', 'De Confiança'), ('champion', 'Campeão')], default='beginner', max_length=50)),
                ('warnings', models.PositiveIntegerField(default=0)),
                ('suspended_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kixikila_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reputation_score'],
            },
        ),
        migrations.AddIndex(
            model_name='kixikilagroup',
            index=models.Index(fields=['status'], name='kixikila_ki_status_110738_idx'),
        ),
        migrations.AddIndex(
            model_name='kixikilagroup',
            index=models.Index(fields=['group_type', 'status'], name='kixikila_ki_group_t_502de1_idx'),
        ),
        migrations.AddIndex(
            model_name='kixikilagroup',
            index=models.Index(fields=['province', 'municipality'], name='kixikila_ki_provinc_424fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='kixikilamembership',
            index=models.Index(fields=['group', 'position'], name='kixikila_ki_group_i_40821f_idx'),
        ),
        migrations.AddIndex(
            model_name='kixikilamembership',
            index=models.Index(fields=['is_active'], name='kixikila_ki_is_acti_ea2670_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kixikilamembership',
            unique_together={('group', 'member')},
        ),
        migrations.AddIndex(
            model_name='kixikilacontribution',
            index=models.Index(fields=['status'], name='kixikila_ki_status_fb674f_idx'),
        ),
        migrations.AddIndex(
            model_name='kixikilacontribution',
            index=models.Index(fields=['membership', 'round'], name='kixikila_ki_members_e3f097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kixikilacontribution',
            unique_together={('membership', 'round')},
        ),
        migrations.AddIndex(
            model_name='kixikilapayout',
            index=models.Index(fields=['status'], name='kixikila_ki_status_fe752b_idx'),
        ),
        migrations.AddIndex(
            model_name='kixikilapayout',
            index=models.Index(fields=['recipient'], name='kixikila_ki_recipie_bd2681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kixikilapayout',
            unique_together={('group', 'round')},
        ),
        migrations.AddIndex(
            model_name='kixikilarating',
            index=models.Index(fields=['trust_level'], name='kixikila_ki_trust_l_fc5a11_idx'),
        ),
    ]
