# Generated by Django 5.0.6 on 2025-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True)),
                ("link", models.URLField(blank=True)),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("all", "Todas"),
                            ("simuladores", "Simuladores"),
                            ("associacao", "Associação"),
                            ("jogos", "Jogos"),
                            ("dashboard", "Dashboard"),
                            ("custom", "Customizada"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
