# Generated by Django 5.0.6 on 2025-12-23 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cert_enrollment", "Inscrição Certificação"),
                            ("marketplace_commission", "Comissão Marketplace"),
                            ("kixikila_platform_fee", "Taxa Kixikila"),
                            ("reality_sponsorship", "Patrocínio Reality"),
                            ("ads", "Publicidade"),
                            ("donations", "Doações"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "created_at"],
                        name="core_revenu_source_10d24c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("cert_pass", "Certificação aprovada"),
                            ("market_order", "Ordem concluída no Marketplace"),
                            ("kix_cycle", "Ciclo Kixikila concluído"),
                            ("reality_winner", "Vencedor de Temporada"),
                            ("game_session", "Sessão de jogo concluída"),
                        ],
                        max_length=50,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_truste_user_id_10337a_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="core_truste_event_t_77595b_idx"
                    ),
                ],
            },
        ),
    ]
