# Generated by Django 5.0.6 on 2025-12-27 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(choices=[('voter', 'Eleitor'), ('participant', 'Participante'), ('mentor', 'Mentor')], max_length=50)),
                ('to_role', models.CharField(choices=[('participant', 'Participante'), ('mentor', 'Mentor')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transitions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_roletransition',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('permission_denied', 'Permission Denied'), ('error', 'Error')], max_length=50)),
                ('resource', models.CharField(max_length=100)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('user_role', models.CharField(blank=True, choices=[('voter', 'Eleitor'), ('participant', 'Participante'), ('mentor', 'Mentor'), ('admin', 'Administrador')], max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_data', models.TextField(blank=True)),
                ('response_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('denied', 'Permission Denied')], max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_auditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['user_role', '-timestamp'], name='core_auditl_user_ro_f2d3e2_idx'), models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'), models.Index(fields=['resource', '-timestamp'], name='core_auditl_resourc_5520ce_idx')],
            },
        ),
    ]
